# DataFrame 병합하기

In [1]:
import pandas as pd
import numpy as np

#### concat 함수를 사용하여 DataFrame 병합
 - 축을 따라 dataframe을 병합
   + axis=0 - 행단위 병합
   + axis=1 - 열단위 병합

#### column명이 같은 경우

In [2]:
df1 = pd.DataFrame({'key1' : np.arange(5), 'value1' : np.random.randn(5)})

In [3]:
df2 = pd.DataFrame({'key1' : np.arange(5), 'value1' : np.random.randn(5)})

In [5]:
df2

   key1    value1
0     0 -0.961339
1     1  0.196438
2     2  0.989123
3     3  0.135729
4     4  0.940792

In [6]:
pd.concat([df1, df2])  # 행 레벨(axis=0)로 병합. 기존 index값은 그대로 유지

   key1    value1
0     0  0.429292
1     1 -0.597786
2     2 -0.713035
3     3  0.643690
4     4 -0.791730
0     0 -0.961339
1     1  0.196438
2     2  0.989123
3     3  0.135729
4     4  0.940792

In [7]:
pd.concat([df1, df2], ignore_index=True)  # 행 레벨(axis=0)로 병합. 기존 index값을 무시하고 새롭게 생성

   key1    value1
0     0  0.429292
1     1 -0.597786
2     2 -0.713035
3     3  0.643690
4     4 -0.791730
5     0 -0.961339
6     1  0.196438
7     2  0.989123
8     3  0.135729
9     4  0.940792

In [8]:
pd.concat([df1, df2], axis=1)  # 열 레벨(axis=1)로 병합

   key1    value1  key1    value1
0     0  0.429292     0 -0.961339
1     1 -0.597786     1  0.196438
2     2 -0.713035     2  0.989123
3     3  0.643690     3  0.135729
4     4 -0.791730     4  0.940792

#### column 명이 다른 경우

In [9]:
df3 = pd.DataFrame({'key2' : np.arange(5), 'value2' : np.random.randn(5)})

In [10]:
pd.concat([df1, df3]) # 행 레벨(axis=0)로 병합

   key1    value1  key2    value2
0   0.0  0.429292   NaN       NaN
1   1.0 -0.597786   NaN       NaN
2   2.0 -0.713035   NaN       NaN
3   3.0  0.643690   NaN       NaN
4   4.0 -0.791730   NaN       NaN
0   NaN       NaN   0.0 -1.094563
1   NaN       NaN   1.0 -1.742376
2   NaN       NaN   2.0 -1.646451
3   NaN       NaN   3.0 -0.822147
4   NaN       NaN   4.0 -0.326920

In [11]:
pd.concat([df1, df3], axis=1) # 열 레벨(axis=1)로 병합

   key1    value1  key2    value2
0     0  0.429292     0 -1.094563
1     1 -0.597786     1 -1.742376
2     2 -0.713035     2 -1.646451
3     3  0.643690     3 -0.822147
4     4 -0.791730     4 -0.326920